spring:
  application:
    name: "Processing Service MS"
  profiles:
    active: dev

server:
  servlet:
    context-path: "/processing/api/v1"

logging:
  level:
    root: INFO
    org:
      springdoc: DEBUG
      mongodb:
        driver: WARN
      apache: ERROR
      springframework:
        web: DEBUG
        boot: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always