# application-dev.yml (Perfil de desenvolvimento)
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/processing-service-db
      auto-index-creation: true
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      uuid-representation: standard
